default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e4
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    summary_freq: 1000
    use_recurrent: false
    sequence_length: 64
    memory_size: 256
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

CarAgent:
    lambd: 0.925
    learning_rate: 1.0e-5
    num_epochs: 5
    buffer_size: 20480
    batch_size: 64
    num_layers: 1
    max_steps: 3.0e6
    epsilon: 0.15
    time_horizon: 256
    hidden_units: 128
    learning_rate_schedule: constant
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.9